// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgKFB69wu2nQOfgROIxeAU2rpRrxXTMRE',
    appId: '1:119004588752:web:da13394f58825b1bacccd5',
    messagingSenderId: '119004588752',
    projectId: 'walkamon-ec4cb',
    authDomain: 'walkamon-ec4cb.firebaseapp.com',
    storageBucket: 'walkamon-ec4cb.firebasestorage.app',
    measurementId: 'G-ZLS2JRK0VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFX9f02lISgJHfJcYu73A9KF_54dQ8EeY',
    appId: '1:119004588752:android:44cbdef95340ccaeacccd5',
    messagingSenderId: '119004588752',
    projectId: 'walkamon-ec4cb',
    storageBucket: 'walkamon-ec4cb.firebasestorage.app',
  );
}
